Jira connector
wearespindle/python-wherescape pull request #1
Opened 2022-03-11 08:51 UTC by Shrikey

DATA-962 - Create JIRA script to fetch tickets per project via the JIRA API

2022-03-11 13:53 UTC, BFJonk requested changes

2022-03-11 13:53 UTC, BFJonk commented on .gitignore
> +config.py
I would have expected instructions on how to use this file in https://github.com/wearespindle/python-wherescape ?

2022-03-11 13:53 UTC, BFJonk commented on wherescape/connectors/jira/readme.md
> +* `jira_user`
If you would have use Extended Properties you would have been able to use the Wheredscape Masking function. 

Even more advanced would be to use a JIRA connection Type with the UI configuration.

2022-03-11 13:53 UTC, BFJonk commented on wherescape/connectors/jira/readme.md
> +```
Where has the try / error Handling gone?

2022-03-11 13:53 UTC, BFJonk commented on wherescape/connectors/jira/readme.md
> +Host scripts to create:
That are lot of host scripts, we could create a script for this?

2022-03-11 13:53 UTC, BFJonk commented on wherescape/connectors/jira/readme.md
> +* python_jira_load_data_issue_incremental
I would have made full / incremental a parameter (?)

2022-03-11 13:53 UTC, BFJonk commented on wherescape/connectors/jira/readme.md
> +the initial load, use the incremental load for better performance.
We could even create a small video & upload it to Youtube or Panopto

2022-03-11 13:53 UTC, BFJonk commented on requirements.txt
>  pyodbc
maybe for the Readme.md: We of course Assume that (a) Python was installed on the wehrescape server (b) The Wherescape Python package is installed

2022-05-02 14:14 UTC, Shrikey commented on .gitignore
> +config.py
This file is actually not used in the repo.

2022-05-02 14:16 UTC, Shrikey commented on wherescape/connectors/jira/readme.md
> +* `jira_user`
Yes, indeed, the JIRA connection type should be the future. Will make a ticket for this.

2022-05-02 14:18 UTC, Shrikey commented on wherescape/connectors/jira/readme.md
> +```
Not necessary anymore with the new logging.

2022-05-02 14:29 UTC, Shrikey commented on wherescape/connectors/jira/readme.md
> +Host scripts to create:
It's only for 1 time, so I don't see the trouble.

2022-05-02 14:37 UTC, Shrikey commented on wherescape/connectors/jira/readme.md
> +the initial load, use the incremental load for better performance.
Yeh, interesting idea.

2022-05-02 14:38 UTC, Shrikey commented on requirements.txt
>  pyodbc
I think that should be obvious already.

2022-05-02 14:44 UTC, Shrikey commented on wherescape/connectors/jira/readme.md
> +* python_jira_load_data_issue_incremental
Might be a future extension.

2022-05-10 15:13 UTC, BFJonk commented on wherescape/connectors/jira/python_jira_load_data.py
> +    base_url = wherescape_instance.base_uri
suggest to rename

2022-05-10 15:13 UTC, BFJonk commented on wherescape/connectors/jira/python_jira_load_data.py
> +from wherescape import WhereScape
why is one called wrapper? and the other not? should be consistent?

2022-05-10 15:13 UTC, BFJonk commented on wherescape/logging.py
>      message_format = logging.Formatter(fmt=fmt, datefmt="%H:%M:%S")
`datefmt` has no date, only hours?

2022-05-10 15:13 UTC, BFJonk commented on wherescape/connectors/jira/__init__.py
> +Module that takes care of the connection to Notion.
JIRA
```suggestion
Module that takes care of the connection to JIRA.
```

2022-06-16 12:03 UTC, closed without merging

2022-08-22 09:18 UTC, Shrikey commented on wherescape/connectors/jira/python_jira_load_data.py
> +from wherescape import WhereScape
Its how we named them in the other repository. WhereScape is more like the main class with own functions and the connectors are more wrappers around the API functions.